version: 2.1

jobs:
  BuildPush:
    parameters:
      imageName:
        description: Reusable way of tagging images for our branch build pipeline
        type: string

    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and Push to ACR
          command: |
            docker build . -t ${registryName}.azurecr.io/<<parameters.imageName>>
            docker login ${registryName}.azurecr.io -u ${registryName} -p ${registryPassword}
            docker push ${registryName}.azurecr.io/<<parameters.imageName>>

workflows:
  version: 2
  SLR_Workflow:
    jobs:
      - BuildPush:
          imageName: latest
          name: BuildPushMaster
          filters:
            branches:
              only: master
      - BuildPush:
          imageName: uat
          name: BuildPushUAT
          filters:
            branches:
              only: uat
      - BuildPush:
          imageName: dev
          name: BuildPushDev
          filters:
            branches:
              only: dev