version: 2.0
jobs:
  BuildPushMaster:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and Push to ACR
          command: |
            docker build . -t ${registryName}.azurecr.io/${frontImageLatest}
            docker login ${registryName}.azurecr.io -u ${registryName} -p ${registryPassword}
            docker push ${registryName}.azurecr.io/${frontImageLatest}
  BuildPushUAT:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and Push to ACR
          command: |
            docker build . -t ${registryName}.azurecr.io/${frontImageUat}
            docker login ${registryName}.azurecr.io -u ${registryName} -p ${registryPassword}
            docker push ${registryName}.azurecr.io/${frontImageUat}
  BuildPushDev:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and Push to ACR
          command: |
            docker build . -t ${registryName}.azurecr.io/${frontImageDev}
            docker login ${registryName}.azurecr.io -u ${registryName} -p ${registryPassword}
            docker push ${registryName}.azurecr.io/${frontImageDev}
workflows:
  version: 2
  CCCP_Workflow:
    jobs:
      - BuildPushMaster:
          filters:
            branches:
              only: master
      - BuildPushUAT:
          filters:
            branches:
              only: uat
      - BuildPushDev:
          filters:
            branches:
              only: dev