version: 2.1
jobs:
  BuildPush:
    description: Build the SLRV front tagged image.
    parameters:
      imageName:
        description: "The name of the SLRV image"
        type: string
        default: slr-image:tag
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and push to ACR.
          command: |
            docker build . -t ${registryName}.azurecr.io/<<parameters.imageName>>
            docker login ${registryName}.azurecr.io -u ${registryName} -p ${registryPassword}
            docker push ${registryName}.azurecr.io/<<parameters.imageName>>
workflows:
  workflow:
    jobs:
      - BuildPush:
          imageName: slr-front:latest
          name: BuildPushMaster
          filters:
            branches:
              only: master
      - BuildPush:
          imageName: slr-front:uat
          name: BuildPushUAT
          filters:
            branches:
              only: uat
      - BuildPush:
          imageName: slr-front:dev
          name: BuildPushDev
          filters:
            branches:
              only: dev